
version: "3.7"

services:
  backend:
    container_name: desafio-conta-digital_backend
    restart: always
    build: .
    environment:
      - APP_ENV=development
      - APP_PORT=9000
    volumes:
      - ./src:/var/www/desafio-conta-digital/src
      - ./test:/var/www/desafio-conta-digital/test
    working_dir: /var/www/desafio-conta-digital
    ports:
      - "9001:9000"
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
  mysql: # Example Service
    container_name: desafio-conta-digital_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=desafio-conta-digital
      - MYSQL_PASSWORD=desafio-conta-digital
      - MYSQL_DATABASE=desafio-conta-digital_docker
    ports:
    - "3308:3306"
    volumes:
    - desafio-conta-digital_mysql_data:/var/lib/mysql
  redis: # Example Service
    container_name: desafio-conta-digital_redis
    restart: always
    image: redis:6.0-alpine
    expose:
      - "6379"
    volumes:
      - desafio-conta-digital_redis_data:/data

volumes:
  desafio-conta-digital_mysql_data:
  desafio-conta-digital_redis_data:

networks:
  default:
    external:
      name: desafio-conta-digital